# Generated by Django 2.1.1 on 2018-09-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders_askQuestion', '0004_auto_20180916_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answeringTheQuestion',
        ),
        migrations.DeleteModel(
            name='questionToBeAnswerd',
        ),
    ]
