# Generated by Django 2.1.1 on 2018-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('user', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(default='', max_length=30)),
                ('LastName', models.CharField(default='', max_length=30)),
                ('answerLanguage', models.CharField(choices=[('1', 'Python'), ('2', 'java'), ('3', 'javaScript'), ('4', 'c++')], default='', max_length=3)),
                ('answerContent', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
