# Generated by Django 2.1.1 on 2018-09-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders_answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
