# Generated by Django 2.1.1 on 2018-09-16 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coders_answers', '0002_auto_20180916_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.AddField(
            model_name='answer',
            name='LastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answerLanguage',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'java'), ('3', 'javaScript')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='usernname',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
