# Generated by Django 2.1.1 on 2018-09-16 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coders_answers', '0004_answer_answercontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='usernname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerd_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
