# Generated by Django 2.1.1 on 2018-09-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders_answers', '0007_auto_20180916_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
