# Generated by Django 2.1.1 on 2018-09-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders_feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecard',
            name='content',
        ),
    ]
