# Generated by Django 2.1.1 on 2018-09-22 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coders_feeds', '0002_remove_codecard_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecard',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
